FROM golang:1.16-alpine
RUN apk add build-base

WORKDIR /coord

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o bin/coord ./cmd/coord

# EXPOSE 56837 59141

CMD [ "./bin/coord" ]




