FROM golang:1.17-alpine
RUN apk add build-base

WORKDIR /coord

COPY go.mod ./
COPY go.sum ./

RUN go mod download

COPY . .

RUN go build -o bin/coord ./cmd/coord
RUN go build -o bin/worker ./cmd/worker

EXPOSE 56837
EXPOSE 9000

CMD [ "./bin/coord" ]




