// source: coord.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.coord.Query', null, global);
goog.exportSymbol('proto.coord.QueryResult', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coord.Query = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.coord.Query.repeatedFields_,
    null
  );
};
goog.inherits(proto.coord.Query, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coord.Query.displayName = 'proto.coord.Query';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.coord.QueryResult = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.coord.QueryResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.coord.QueryResult.displayName = 'proto.coord.QueryResult';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.coord.Query.repeatedFields_ = [3];

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.coord.Query.prototype.toObject = function (opt_includeInstance) {
    return proto.coord.Query.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.coord.Query} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.coord.Query.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        clientid: jspb.Message.getFieldWithDefault(msg, 1, ''),
        querytype: jspb.Message.getFieldWithDefault(msg, 2, ''),
        nodesList:
          (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
        graph: jspb.Message.getFieldWithDefault(msg, 4, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coord.Query}
 */
proto.coord.Query.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coord.Query();
  return proto.coord.Query.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coord.Query} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coord.Query}
 */
proto.coord.Query.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString());
        msg.setClientid(value);
        break;
      case 2:
        var value = /** @type {string} */ (reader.readString());
        msg.setQuerytype(value);
        break;
      case 3:
        var value = /** @type {!Array<number>} */ (reader.readPackedUint64());
        msg.setNodesList(value);
        break;
      case 4:
        var value = /** @type {string} */ (reader.readString());
        msg.setGraph(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coord.Query.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.coord.Query.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coord.Query} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coord.Query.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getClientid();
  if (f.length > 0) {
    writer.writeString(1, f);
  }
  f = message.getQuerytype();
  if (f.length > 0) {
    writer.writeString(2, f);
  }
  f = message.getNodesList();
  if (f.length > 0) {
    writer.writePackedUint64(3, f);
  }
  f = message.getGraph();
  if (f.length > 0) {
    writer.writeString(4, f);
  }
};

/**
 * optional string ClientId = 1;
 * @return {string}
 */
proto.coord.Query.prototype.getClientid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''));
};

/**
 * @param {string} value
 * @return {!proto.coord.Query} returns this
 */
proto.coord.Query.prototype.setClientid = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};

/**
 * optional string QueryType = 2;
 * @return {string}
 */
proto.coord.Query.prototype.getQuerytype = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ''));
};

/**
 * @param {string} value
 * @return {!proto.coord.Query} returns this
 */
proto.coord.Query.prototype.setQuerytype = function (value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};

/**
 * repeated uint64 Nodes = 3;
 * @return {!Array<number>}
 */
proto.coord.Query.prototype.getNodesList = function () {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 3));
};

/**
 * @param {!Array<number>} value
 * @return {!proto.coord.Query} returns this
 */
proto.coord.Query.prototype.setNodesList = function (value) {
  return jspb.Message.setField(this, 3, value || []);
};

/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.coord.Query} returns this
 */
proto.coord.Query.prototype.addNodes = function (value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.coord.Query} returns this
 */
proto.coord.Query.prototype.clearNodesList = function () {
  return this.setNodesList([]);
};

/**
 * optional string Graph = 4;
 * @return {string}
 */
proto.coord.Query.prototype.getGraph = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''));
};

/**
 * @param {string} value
 * @return {!proto.coord.Query} returns this
 */
proto.coord.Query.prototype.setGraph = function (value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.coord.QueryResult.prototype.toObject = function (opt_includeInstance) {
    return proto.coord.QueryResult.toObject(opt_includeInstance, this);
  };

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.coord.QueryResult} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.coord.QueryResult.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        query:
          (f = msg.getQuery()) &&
          proto.coord.Query.toObject(includeInstance, f),
        result:
          (f = msg.getResult()) &&
          google_protobuf_any_pb.Any.toObject(includeInstance, f),
        error: jspb.Message.getFieldWithDefault(msg, 3, ''),
      };

    if (includeInstance) {
      obj.$jspbMessageInstance = msg;
    }
    return obj;
  };
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.coord.QueryResult}
 */
proto.coord.QueryResult.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.coord.QueryResult();
  return proto.coord.QueryResult.deserializeBinaryFromReader(msg, reader);
};

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.coord.QueryResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.coord.QueryResult}
 */
proto.coord.QueryResult.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
      case 1:
        var value = new proto.coord.Query();
        reader.readMessage(
          value,
          proto.coord.Query.deserializeBinaryFromReader
        );
        msg.setQuery(value);
        break;
      case 2:
        var value = new google_protobuf_any_pb.Any();
        reader.readMessage(
          value,
          google_protobuf_any_pb.Any.deserializeBinaryFromReader
        );
        msg.setResult(value);
        break;
      case 3:
        var value = /** @type {string} */ (reader.readString());
        msg.setError(value);
        break;
      default:
        reader.skipField();
        break;
    }
  }
  return msg;
};

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.coord.QueryResult.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter();
  proto.coord.QueryResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.coord.QueryResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.coord.QueryResult.serializeBinaryToWriter = function (message, writer) {
  var f = undefined;
  f = message.getQuery();
  if (f != null) {
    writer.writeMessage(1, f, proto.coord.Query.serializeBinaryToWriter);
  }
  f = message.getResult();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f.length > 0) {
    writer.writeString(3, f);
  }
};

/**
 * optional Query Query = 1;
 * @return {?proto.coord.Query}
 */
proto.coord.QueryResult.prototype.getQuery = function () {
  return /** @type{?proto.coord.Query} */ (
    jspb.Message.getWrapperField(this, proto.coord.Query, 1)
  );
};

/**
 * @param {?proto.coord.Query|undefined} value
 * @return {!proto.coord.QueryResult} returns this
 */
proto.coord.QueryResult.prototype.setQuery = function (value) {
  return jspb.Message.setWrapperField(this, 1, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.coord.QueryResult} returns this
 */
proto.coord.QueryResult.prototype.clearQuery = function () {
  return this.setQuery(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coord.QueryResult.prototype.hasQuery = function () {
  return jspb.Message.getField(this, 1) != null;
};

/**
 * optional google.protobuf.Any Result = 2;
 * @return {?proto.google.protobuf.Any}
 */
proto.coord.QueryResult.prototype.getResult = function () {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 2)
  );
};

/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.coord.QueryResult} returns this
 */
proto.coord.QueryResult.prototype.setResult = function (value) {
  return jspb.Message.setWrapperField(this, 2, value);
};

/**
 * Clears the message field making it undefined.
 * @return {!proto.coord.QueryResult} returns this
 */
proto.coord.QueryResult.prototype.clearResult = function () {
  return this.setResult(undefined);
};

/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.coord.QueryResult.prototype.hasResult = function () {
  return jspb.Message.getField(this, 2) != null;
};

/**
 * optional string Error = 3;
 * @return {string}
 */
proto.coord.QueryResult.prototype.getError = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ''));
};

/**
 * @param {string} value
 * @return {!proto.coord.QueryResult} returns this
 */
proto.coord.QueryResult.prototype.setError = function (value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};

// goog.object.extend(exports, proto.coord);
module.exports = proto.coord;
