// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: coord.proto

package coord

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CoordClient is the client API for Coord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordClient interface {
	StartQuery(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResult, error)
}

type coordClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordClient(cc grpc.ClientConnInterface) CoordClient {
	return &coordClient{cc}
}

func (c *coordClient) StartQuery(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResult, error) {
	out := new(QueryResult)
	err := c.cc.Invoke(ctx, "/coord.Coord/StartQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordServer is the server API for Coord service.
// All implementations must embed UnimplementedCoordServer
// for forward compatibility
type CoordServer interface {
	StartQuery(context.Context, *Query) (*QueryResult, error)
	mustEmbedUnimplementedCoordServer()
}

// UnimplementedCoordServer must be embedded to have forward compatible implementations.
type UnimplementedCoordServer struct {
}

func (UnimplementedCoordServer) StartQuery(context.Context, *Query) (*QueryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartQuery not implemented")
}
func (UnimplementedCoordServer) mustEmbedUnimplementedCoordServer() {}

// UnsafeCoordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordServer will
// result in compilation errors.
type UnsafeCoordServer interface {
	mustEmbedUnimplementedCoordServer()
}

func RegisterCoordServer(s grpc.ServiceRegistrar, srv CoordServer) {
	s.RegisterService(&Coord_ServiceDesc, srv)
}

func _Coord_StartQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordServer).StartQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/coord.Coord/StartQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordServer).StartQuery(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

// Coord_ServiceDesc is the grpc.ServiceDesc for Coord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coord.Coord",
	HandlerType: (*CoordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartQuery",
			Handler:    _Coord_StartQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coord.proto",
}
