// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.13.0
// source: coord.proto

package coord

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QUERY_TYPE int32

const (
	QUERY_TYPE_PAGE_RANK     QUERY_TYPE = 0
	QUERY_TYPE_SHORTEST_PATH QUERY_TYPE = 1
)

// Enum value maps for QUERY_TYPE.
var (
	QUERY_TYPE_name = map[int32]string{
		0: "PAGE_RANK",
		1: "SHORTEST_PATH",
	}
	QUERY_TYPE_value = map[string]int32{
		"PAGE_RANK":     0,
		"SHORTEST_PATH": 1,
	}
)

func (x QUERY_TYPE) Enum() *QUERY_TYPE {
	p := new(QUERY_TYPE)
	*p = x
	return p
}

func (x QUERY_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QUERY_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_coord_proto_enumTypes[0].Descriptor()
}

func (QUERY_TYPE) Type() protoreflect.EnumType {
	return &file_coord_proto_enumTypes[0]
}

func (x QUERY_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QUERY_TYPE.Descriptor instead.
func (QUERY_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{0}
}

type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  string     `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	QueryType QUERY_TYPE `protobuf:"varint,2,opt,name=QueryType,proto3,enum=coord.QUERY_TYPE" json:"QueryType,omitempty"`
	Nodes     []uint64   `protobuf:"varint,3,rep,packed,name=Nodes,proto3" json:"Nodes,omitempty"`
	Graph     string     `protobuf:"bytes,4,opt,name=Graph,proto3" json:"Graph,omitempty"`
	TableName string     `protobuf:"bytes,5,opt,name=TableName,proto3" json:"TableName,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{0}
}

func (x *Query) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Query) GetQueryType() QUERY_TYPE {
	if x != nil {
		return x.QueryType
	}
	return QUERY_TYPE_PAGE_RANK
}

func (x *Query) GetNodes() []uint64 {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Query) GetGraph() string {
	if x != nil {
		return x.Graph
	}
	return ""
}

func (x *Query) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query  *Query  `protobuf:"bytes,1,opt,name=Query,proto3" json:"Query,omitempty"`
	Result float64 `protobuf:"fixed64,2,opt,name=Result,proto3" json:"Result,omitempty"`
	Error  string  `protobuf:"bytes,3,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResult) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *QueryResult) GetResult() float64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *QueryResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VertexMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceVertexId uint64 `protobuf:"varint,1,opt,name=SourceVertexId,proto3" json:"SourceVertexId,omitempty"`
	DestVertexId   uint64 `protobuf:"varint,2,opt,name=DestVertexId,proto3" json:"DestVertexId,omitempty"`
	Value          int64  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *VertexMessage) Reset() {
	*x = VertexMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VertexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertexMessage) ProtoMessage() {}

func (x *VertexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertexMessage.ProtoReflect.Descriptor instead.
func (*VertexMessage) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{2}
}

func (x *VertexMessage) GetSourceVertexId() uint64 {
	if x != nil {
		return x.SourceVertexId
	}
	return 0
}

func (x *VertexMessage) GetDestVertexId() uint64 {
	if x != nil {
		return x.DestVertexId
	}
	return 0
}

func (x *VertexMessage) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type VertexMessages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VertexMessages []*VertexMessage `protobuf:"bytes,1,rep,name=vertexMessages,proto3" json:"vertexMessages,omitempty"`
}

func (x *VertexMessages) Reset() {
	*x = VertexMessages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VertexMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VertexMessages) ProtoMessage() {}

func (x *VertexMessages) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VertexMessages.ProtoReflect.Descriptor instead.
func (*VertexMessages) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{3}
}

func (x *VertexMessages) GetVertexMessages() []*VertexMessage {
	if x != nil {
		return x.VertexMessages
	}
	return nil
}

type QueryProgressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryProgressRequest) Reset() {
	*x = QueryProgressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProgressRequest) ProtoMessage() {}

func (x *QueryProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProgressRequest.ProtoReflect.Descriptor instead.
func (*QueryProgressRequest) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{4}
}

type QueryProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SuperstepNumber uint64                     `protobuf:"varint,1,opt,name=superstepNumber,proto3" json:"superstepNumber,omitempty"`
	Messages        map[uint64]*VertexMessages `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *QueryProgressResponse) Reset() {
	*x = QueryProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryProgressResponse) ProtoMessage() {}

func (x *QueryProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryProgressResponse.ProtoReflect.Descriptor instead.
func (*QueryProgressResponse) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{5}
}

func (x *QueryProgressResponse) GetSuperstepNumber() uint64 {
	if x != nil {
		return x.SuperstepNumber
	}
	return 0
}

func (x *QueryProgressResponse) GetMessages() map[uint64]*VertexMessages {
	if x != nil {
		return x.Messages
	}
	return nil
}

type WorkerVertices struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertices []uint64 `protobuf:"varint,1,rep,packed,name=vertices,proto3" json:"vertices,omitempty"`
}

func (x *WorkerVertices) Reset() {
	*x = WorkerVertices{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerVertices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerVertices) ProtoMessage() {}

func (x *WorkerVertices) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerVertices.ProtoReflect.Descriptor instead.
func (*WorkerVertices) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{6}
}

func (x *WorkerVertices) GetVertices() []uint64 {
	if x != nil {
		return x.Vertices
	}
	return nil
}

type FetchGraphRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchGraphRequest) Reset() {
	*x = FetchGraphRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchGraphRequest) ProtoMessage() {}

func (x *FetchGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchGraphRequest.ProtoReflect.Descriptor instead.
func (*FetchGraphRequest) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{7}
}

type FetchGraphResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerVertices map[uint32]*WorkerVertices `protobuf:"bytes,1,rep,name=workerVertices,proto3" json:"workerVertices,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *FetchGraphResponse) Reset() {
	*x = FetchGraphResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_coord_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchGraphResponse) ProtoMessage() {}

func (x *FetchGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coord_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchGraphResponse.ProtoReflect.Descriptor instead.
func (*FetchGraphResponse) Descriptor() ([]byte, []int) {
	return file_coord_proto_rawDescGZIP(), []int{8}
}

func (x *FetchGraphResponse) GetWorkerVertices() map[uint32]*WorkerVertices {
	if x != nil {
		return x.WorkerVertices
	}
	return nil
}

var File_coord_proto protoreflect.FileDescriptor

var file_coord_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63,
	0x6f, 0x6f, 0x72, 0x64, 0x22, 0x9e, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1a,
	0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x52, 0x09, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x4e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x04, 0x52, 0x05, 0x4e, 0x6f, 0x64, 0x65,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x5f, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x71, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x12,
	0x22, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x56, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4e, 0x0a, 0x0e, 0x56, 0x65, 0x72,
	0x74, 0x65, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0e, 0x76,
	0x65, 0x72, 0x74, 0x65, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x56, 0x65, 0x72, 0x74,
	0x65, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x0e, 0x76, 0x65, 0x72, 0x74, 0x65,
	0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0xdd, 0x01, 0x0a, 0x15, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x75, 0x70, 0x65, 0x72, 0x73, 0x74, 0x65, 0x70, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0f, 0x73, 0x75, 0x70, 0x65, 0x72, 0x73, 0x74, 0x65, 0x70, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x46, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x52, 0x0a,
	0x0d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x2b, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x2c, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x08, 0x76, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x22,
	0x13, 0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0xc5, 0x01, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63, 0x68, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x77,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63,
	0x65, 0x73, 0x1a, 0x58, 0x0a, 0x13, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74,
	0x69, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x6f,
	0x72, 0x64, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x56, 0x65, 0x72, 0x74, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x2e, 0x0a, 0x0a,
	0x51, 0x55, 0x45, 0x52, 0x59, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x0d, 0x0a, 0x09, 0x50, 0x41,
	0x47, 0x45, 0x5f, 0x52, 0x41, 0x4e, 0x4b, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x48, 0x4f,
	0x52, 0x54, 0x45, 0x53, 0x54, 0x5f, 0x50, 0x41, 0x54, 0x48, 0x10, 0x01, 0x32, 0xce, 0x01, 0x0a,
	0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x30, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x0c, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4e, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x2e, 0x63, 0x6f, 0x6f, 0x72,
	0x64, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a, 0x0a, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x47, 0x72, 0x61, 0x70, 0x68, 0x12, 0x18, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x47, 0x72, 0x61, 0x70, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x47, 0x72,
	0x61, 0x70, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_coord_proto_rawDescOnce sync.Once
	file_coord_proto_rawDescData = file_coord_proto_rawDesc
)

func file_coord_proto_rawDescGZIP() []byte {
	file_coord_proto_rawDescOnce.Do(func() {
		file_coord_proto_rawDescData = protoimpl.X.CompressGZIP(file_coord_proto_rawDescData)
	})
	return file_coord_proto_rawDescData
}

var file_coord_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_coord_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_coord_proto_goTypes = []interface{}{
	(QUERY_TYPE)(0),               // 0: coord.QUERY_TYPE
	(*Query)(nil),                 // 1: coord.Query
	(*QueryResult)(nil),           // 2: coord.QueryResult
	(*VertexMessage)(nil),         // 3: coord.VertexMessage
	(*VertexMessages)(nil),        // 4: coord.VertexMessages
	(*QueryProgressRequest)(nil),  // 5: coord.QueryProgressRequest
	(*QueryProgressResponse)(nil), // 6: coord.QueryProgressResponse
	(*WorkerVertices)(nil),        // 7: coord.WorkerVertices
	(*FetchGraphRequest)(nil),     // 8: coord.FetchGraphRequest
	(*FetchGraphResponse)(nil),    // 9: coord.FetchGraphResponse
	nil,                           // 10: coord.QueryProgressResponse.MessagesEntry
	nil,                           // 11: coord.FetchGraphResponse.WorkerVerticesEntry
}
var file_coord_proto_depIdxs = []int32{
	0,  // 0: coord.Query.QueryType:type_name -> coord.QUERY_TYPE
	1,  // 1: coord.QueryResult.Query:type_name -> coord.Query
	3,  // 2: coord.VertexMessages.vertexMessages:type_name -> coord.VertexMessage
	10, // 3: coord.QueryProgressResponse.messages:type_name -> coord.QueryProgressResponse.MessagesEntry
	11, // 4: coord.FetchGraphResponse.workerVertices:type_name -> coord.FetchGraphResponse.WorkerVerticesEntry
	4,  // 5: coord.QueryProgressResponse.MessagesEntry.value:type_name -> coord.VertexMessages
	7,  // 6: coord.FetchGraphResponse.WorkerVerticesEntry.value:type_name -> coord.WorkerVertices
	1,  // 7: coord.Coord.StartQuery:input_type -> coord.Query
	5,  // 8: coord.Coord.QueryProgress:input_type -> coord.QueryProgressRequest
	8,  // 9: coord.Coord.FetchGraph:input_type -> coord.FetchGraphRequest
	2,  // 10: coord.Coord.StartQuery:output_type -> coord.QueryResult
	6,  // 11: coord.Coord.QueryProgress:output_type -> coord.QueryProgressResponse
	9,  // 12: coord.Coord.FetchGraph:output_type -> coord.FetchGraphResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_coord_proto_init() }
func file_coord_proto_init() {
	if File_coord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_coord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VertexMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VertexMessages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProgressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerVertices); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchGraphRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_coord_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchGraphResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_coord_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coord_proto_goTypes,
		DependencyIndexes: file_coord_proto_depIdxs,
		EnumInfos:         file_coord_proto_enumTypes,
		MessageInfos:      file_coord_proto_msgTypes,
	}.Build()
	File_coord_proto = out.File
	file_coord_proto_rawDesc = nil
	file_coord_proto_goTypes = nil
	file_coord_proto_depIdxs = nil
}
